name: 'Hello World: Composite'
description: 'Composite action'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'composite'
  steps:
    - uses: dylanvgils/actions/docker@main
      id: hello
      with:
        who-to-greet: ${{ inputs.who-to-greet }}
    - shell: bash
      run: |
        echo "Echo from the composite action" 
        echo "The time was: ${{ steps.hello.outputs.time }}"
    - uses: dylanvgils/actions/script@main
      with:
        time-of-greeting: ${{ steps.hello.outputs.time }}
    - shell: bash
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/dylanvgils/actions/issues/1/comments \
          -f body='Hello World, this is a test comment'
