name: 'Hello World: Composite'
description: 'Composite action'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'composite'
  steps:
    - uses: dylanvgils/actions/docker@main
      with:
        who-to-greet: ${{ inputs.who-to-greet }}
    - shell: bash
      run: echo "Hello world"