on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        uses: dylanvgils/actions@main
        with:
          who-to-greet: 'Mona the Octocat'